PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dblp: <https://dblp.org/rdf/schema#>

SELECT DISTINCT ?id ?value ?tags WHERE {
  # Get ids and their frequencies for score
  {
    SELECT ?id (SUM(?freq) AS ?score) WHERE {
      {
        SELECT ?id ("SUB" AS ?pos) (COUNT(?id) AS ?freq) WHERE {
          ?id rdfs:label [] .
          ?id ?p ?o
        } GROUP BY ?id
      } UNION {
        SELECT ?id ("OBJ" AS ?pos) (COUNT(?id) AS ?freq) WHERE {
          ?id rdfs:label [] .
          ?s ?p ?id .
          FILTER(ISIRI(?id))
        } GROUP BY ?id
      }
    } GROUP BY ?id
  }

  {
    # Get label
    ?id rdfs:label ?value .
    BIND("main" AS ?tags)
  } UNION {
    # Get aliases
    ?id dblp:primaryCreatorName ?value
  }
}
ORDER BY DESC(?score) ?id DESC(?tags)
