PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?id ?value ?tags WHERE {
  # Get ids and their frequencies for score
  {
    SELECT ?id (SUM(?freq) AS ?score) WHERE {
      {
        SELECT ?id ("SUB" AS ?pos) (COUNT(?id) AS ?freq) WHERE {
          ?id rdfs:label ?label .
          FILTER(LANG(?label) = "en") .
          ?id ?p ?o
        } GROUP BY ?id
      } UNION {
        SELECT ?id ("OBJ" AS ?pos) (COUNT(?id) AS ?freq) WHERE {
          ?id rdfs:label ?label .
          FILTER(LANG(?label) = "en") .
          ?s ?p ?id .
          FILTER(ISIRI(?id))
        } GROUP BY ?id
      }
    } GROUP BY ?id
  }

  {
    # Get label
    ?id rdfs:label ?value .
    FILTER(LANG(?value) = "en")
    BIND("main" AS ?tags)
  } UNION {
    # Get aliases
    ?id dbp:synonyms ?value .
    FILTER(LANG(?value) = "en")
  } UNION {
    ?id dbo:alias ?value .
    FILTER(LANG(?value) = "en")
  } UNION {
    ?id dbo:alternativeName ?value .
    FILTER(LANG(?value) = "en")
  } UNION {
    ?id foaf:nick ?value .
    FILTER(LANG(?value) = "en")
  }
}
ORDER BY DESC(?score) ?id DESC(?tags)
