PREFIX fb: <http://rdf.freebase.com/ns/>

SELECT DISTINCT ?id ?value ?tags WHERE {
  # Get ids and their frequencies for score
  { SELECT ?id (COUNT(?id) AS ?score) WHERE { ?s ?id ?o } GROUP BY ?id } 

  # e.g. fb:time.event.next_in_series will be excluded if not optional
  OPTIONAL { 
    {
      ?id @en@fb:type.object.name ?value .
      BIND("main" AS ?tags)
    } UNION {
      ?id @en@fb:type.object.name ?value .
    }
  }

  FILTER(STRSTARTS(STR(?id), "http://rdf.freebase.com/ns/"))
}
ORDER BY DESC(?score) ?id DESC(?tags)
