PREFIX fb: <http://rdf.freebase.com/ns/>

SELECT DISTINCT ?id ?value ?tags WHERE {
  # Get ids and their frequencies for score
  {
    SELECT ?id (SUM(?freq) AS ?score) WHERE {
      {
        SELECT ?id ("SUB" AS ?pos) (COUNT(?id) AS ?freq) WHERE {
          ?id @en@fb:type.object.name ?label . 
          ?id ?p ?o 
        } GROUP BY ?id 
      } UNION {
        SELECT ?id ("OBJ" AS ?pos) (COUNT(?id) AS ?freq) WHERE {
          ?id @en@fb:type.object.name ?label . 
          ?s ?p ?id .
          FILTER(ISIRI(?id)) 
        } GROUP BY ?id
      }
    } GROUP BY ?id
  }

  {
    # Get label
    ?id @en@fb:type.object.name ?value .
    BIND("main" AS ?tags)
  } UNION {
    # Get aliases
    ?id @en@fb:common.topic.alias ?value
  }
}
ORDER BY DESC(?score) ?id DESC(?tags)
