PREFIX fb: <http://rdf.freebase.com/ns/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?id ?value ?type WHERE {
  {
    VALUES ?id { {IDS} }
    ?id @en@fb:type.object.name ?value
    BIND("label" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id @en@fb:common.topic.alias ?value
    BIND("alias" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id fb:type.property.schema/@en@rdfs:label ?schema.
    FILTER(LANGMATCHES(LANG(?schema), "en"))
    BIND(CONCAT("is part of schema ", ?schema) AS ?value)
    BIND("info" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id fb:type.property.expected_type/@en@rdfs:label ?type .
    BIND(CONCAT("links to type ", ?type) AS ?value)
    BIND("info" AS ?type)
  }
}
ORDER BY ?id ?type ?value
