PREFIX rdfs: <https://www.w3.org/2000/01/rdf-schema#>
PREFIX gptkb: <https://gptkb.org/entity/>
PREFIX gptkbp: <https://gptkb.org/prop/>

SELECT
  ?id
  (SAMPLE(?label) AS ?main_label)
  (GROUP_CONCAT(DISTINCT ?alias; SEPARATOR=";;;") AS ?aliases)
WHERE {
  # Get props and their frequencies for score
  { 
    SELECT ?id (SUM(?freq) AS ?total_freq) WHERE {
      { SELECT ?id ("SUB" AS ?pos) (COUNT(?id) AS ?freq) WHERE { ?id ?p ?o } GROUP BY ?id } 
      UNION
      { SELECT ?id ("OBJ" AS ?pos) (COUNT(?id) AS ?freq) WHERE { ?s ?p ?id . FILTER(ISIRI(?id)) } GROUP BY ?id }
    } GROUP BY ?id
  } 

  # Get label
  OPTIONAL { ?id rdfs:label ?label }

  # Get aliases
  OPTIONAL { ?id gptkbp:alternativeName ?alias }
}
GROUP BY ?id
ORDER BY DESC(MAX(?total_freq))
