PREFIX rdfs: <https://www.w3.org/2000/01/rdf-schema#>
PREFIX gptkb: <https://gptkb.org/entity/>
PREFIX gptkbp: <https://gptkb.org/prop/>

SELECT DISTINCT ?id ?value ?tags WHERE {
  # Get props and their frequencies for score
  {
    SELECT ?id (COUNT(?id) AS ?score) WHERE {
      ?s ?id ?o
    } GROUP BY ?id
  }

  OPTIONAL {
    {
      # Get label
      ?id rdfs:label ?value .
      BIND("main" AS ?tags)
    } UNION {
      # Get aliases
      ?id gptkbp:alternativeName ?value
    }
  }
}
ORDER BY DESC(?score) ?id DESC(?tags)
