PREFIX osmkey: <https://www.openstreetmap.org/wiki/Key:>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?id ?value ?type WHERE {
  # Get additional information
  {
    VALUES ?id { {IDS} }
    ?id osmkey:name ?value
    BIND("label" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id osmkey:short_name ?value
    BIND("alias" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id osmkey:name:en ?value
    BIND("alias" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id osmkey:name:de ?value
    BIND("alias" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id osmkey:admin_title ?value
    BIND("info" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id osmkey:description ?value
    BIND("info" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id osmkey:amenity ?value
    BIND("info" AS ?type)
  }
}
ORDER BY ?id ?type ?value
