PREFIX osmkey: <https://www.openstreetmap.org/wiki/Key:>

SELECT DISTINCT ?id ?value ?tags WHERE {
  # Get ids and their frequencies for score
  {
    SELECT ?id (SUM(?freq) AS ?score) WHERE {
      {
        SELECT ?id ("SUB" AS ?pos) (COUNT(?id) AS ?freq) WHERE {
          ?id osmkey:name [] .
          ?id ?p ?o
        } GROUP BY ?id
      } UNION {
        SELECT ?id ("OBJ" AS ?pos) (COUNT(?id) AS ?freq) WHERE {
          ?id osmkey:name [] .
          ?s ?p ?id .
          FILTER(ISIRI(?id))
        } GROUP BY ?id
      }
    } GROUP BY ?id
  }

  {
    # Get label
    ?id osmkey:name ?value .
    BIND("main" AS ?tags)
  } UNION {
    # Get aliases
    ?id osmkey:short_name ?value
  } UNION {
    ?id osmkey:name:en ?value
  } UNION {
    ?id osmkey:name:de ?value
  }
}
ORDER BY DESC(?score) ?id DESC(?tags)
