PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX up: <http://purl.uniprot.org/core/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?id ?value ?tags WHERE {
  # Get ids and their frequencies for score
  {
    SELECT ?id (SUM(?freq) AS ?score) WHERE {
      {
        SELECT ?id ("SUB" AS ?pos) (COUNT(?id) AS ?freq) WHERE {
          ?id rdf:type ?type
          FILTER(?type IN (
            owl:Class,
            owl:DatatypeProperty,
            up:Taxon,
            up:Database,
            up:Concept,
            up:Enzyme,
            up:Proteome,
            up:Chromosome
          ))
          ?id ?p ?o
        } GROUP BY ?id
      } UNION {
        SELECT ?id ("OBJ" AS ?pos) (COUNT(?id) AS ?freq) WHERE {
          ?id rdf:type ?type
          FILTER(?type IN (
            owl:Class,
            owl:DatatypeProperty,
            up:Taxon,
            up:Database,
            up:Concept,
            up:Enzyme,
            up:Proteome,
            up:Chromosome
          ))
          ?s ?p ?id .
          FILTER(ISIRI(?id))
        } GROUP BY ?id
      }
    } GROUP BY ?id
  }

  # Filter ids
  ?id rdf:type ?type
  FILTER(?type IN (
    owl:Class,
    owl:DatatypeProperty,
    up:Taxon,
    up:Database,
    up:Concept,
    up:Enzyme,
    up:Proteome,
    up:Chromosome
  ))

  {
    # Get label
    ?id rdfs:label ?value .
    BIND("main" AS ?tags)
  } UNION {
    # Get aliases
    ?id up:scientificName ?value
  } UNION {
    ?id up:otherName ?value
  } UNION {
    ?id up:commonName ?value
  } UNION {
    ?id up:mnemonic ?value
  } UNION {
    ?id up:synonym ?value
  } UNION {
    ?id <http://www.geneontology.org/formats/oboInOwl#hasExactSynonym> ?value
  } UNION {
    ?id <http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym> ?value
  }
}
ORDER BY DESC(?score) ?id DESC(?tags)
