PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT ?id ?value ?type WHERE {
  # Get additional information
  {
    VALUES ?id { {IDS} }
    ?id rdfs:label ?value
    BIND("label" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id skos:altLabel ?value
    BIND("alias" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id schema:description ?value
    BIND("info" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id wdt:P279/rdfs:label ?supclass
    FILTER(LANG(?supclass) = "en")
    BIND(STRLANG(CONCAT("is subclass of ", ?supclass), "en") AS ?value)
    BIND("info" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id wdt:P31/rdfs:label ?inst
    FILTER(LANG(?inst) = "en")
    BIND(STRLANG(CONCAT("is instance of ", ?inst), "en") AS ?value)
    BIND("info" AS ?type)
  } UNION {
    VALUES ?id { {IDS} }
    ?id wdt:P106/rdfs:label ?job
    FILTER(LANG(?job) = "en")
    BIND(STRLANG(CONCAT("has occupation ", ?job), "en") AS ?value)
    BIND("info" AS ?type)
  }

  FILTER(LANG(?value) = "en")
}
ORDER BY ?id ?type ?value
